site_name: XP 分类项目 | 第二期
site_url: https://furinalt.github.io/xp-taxonomy/site/
site_author: 曦涟Elysielle
site_description: >-
  XP 分类项目 | 第二期

repo_name: xp-taxonomy
repo_url: https://github.com/FurinaLT/xp-taxonomy

theme:
  name: material
  language: zh
  favicon: assets/images/favicon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.instant # 即时加载
    - navigation.instant.progress # 进度指示器
    - navigation.sections # 章节折叠
    - navigation.tracking
    - navigation.indexes # 章节索引页
    - navigation.top # 返回顶部
    - navigation.footer
    - navigation.tabs
    - navigation.path # 面包屑
    # - navigation.prune # 导航修剪
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.icons
  
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default # 配色方案
    primary: indigo # 主色调
    accent: deep purple # 强调色
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode

font:
  text: Roboto Slab
  code: Roboto Mono
icon:
  repo: fontawesome/brands/github
  logo: fontawesome/solid/cube

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - md_in_html
  - footnotes
  - toc:
      permalink: true
      title: 章节目录

plugins:
  - search
  - glightbox
  - minify
  - graph
#   - git-revision-date-localized:
#       fallback_to_build_date: true

extra_css:
  - assets/stylesheets/extra.css

extra:
  icons:
    - fontawesome
  extra:

copyright: >
  本站部分内容来源于第三方知识库，依据
  <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/" target="_blank">CC BY-NC-SA 3.0 CN</a>
  许可协议使用，原始来源与是否修改已在各词条中标明。<br>站主邮箱：spicyl114514@gmail.com

nav:
  - 首页:
    - 前言: index.md
  - 产生性质:
    - 产生性质: 0/1.md
    - 认知与情绪:
      - 恶堕: 0/189.md
    - 场景:
      - 室内类:
        - 教室: 0/142.md
        - 浴室: 0/70.md
      - 室外类:
        - 沙滩: 0/73.md
    - 外貌与表象:
      - 绘制或表面表现:
        - 下腹部定规: 0/224.md
        - 人体彩绘: 0/102.md
        - 淫文: 0/200.md
        - 身体涂鸦: 0/104.md
      - 外表:
        - 头部:
          - 异色眼白: 0/213.md
        - 肤色:
          - 褐色皮肤: 0/216.md
          - 黑色皮肤: 0/215.md
        - 躯干:
          - 黑乳头: 0/212.md
    - 性别相关:
      - 性取向:
        - 百合: 0/114.md
    - 服饰:
      - 常见领域:
        - 职业服装:
          - 兔女郎: 0/119.md
          - 商务套装: 0/120.md
          - 小丑: 0/175.md
          - 拉拉队服: 0/136.md
        - 风格:
          - 圣诞装: 0/140.md
          - 婚纱: 0/117.md
      - 服装细分:
        - 上下一体:
          - 全身紧身衣: 0/105.md
          - 围裙: 0/43.md
          - 旗袍: 0/138.md
          - 泳装:
            - 比基尼: 0/91.md
        - 上装:
          - 紧身胸衣: 0/196.md
          - 性相关:
            - 乳交洞: 0/174.md
        - 下装:
          - 灯笼裤: 0/98.md
        - 内衣:
          - 创可贴: 0/69.md
          - 绷带: 0/68.md
        - 头部穿戴:
          - 眼罩: 0/96.md
          - 项圈:
            - 项圈: 0/181.md
            - 洗脑项圈: 0/182.md
        - 性器相关:
          - 阴茎环: 0/176.md
          - 阴茎袜: 0/178.md
    - 物件与设备:
      - 居家物件:
        - 抱枕: 0/214.md
      - 性物品:
        - 夹钳: 0/141.md
        - 避孕套: 0/183.md
        - 采精支架: 0/88.md
        - 肛塞:
          - 肛塞: 0/121.md
          - 宝石肛塞: 0/124.md
          - 尾巴肛塞: 0/123.md
          - 肛珠: 0/122.md
      - 性设备:
        - 机械触手: 0/195.md
        - 震动椅: 0/194.md
        - 高潮自行车: 0/193.md
    - 物种与身体结构:
      - 物种:
        - Furry: 0/35.md
        - 天使: 0/32.md
        - 恶魔: 0/220.md
        - 人外:
          - 半人马: 0/130.md
          - 兽娘:
            - 兽娘: 0/199.md
            - 牛娘: 0/198.md
            - 猫娘: 0/128.md
        - 人造生命:
          - 克隆体: 0/146.md
        - 性别变体:
          - Cuntboy: 0/210.md
          - 扶她:
            - 扶她: 0/65.md
            - 无睾丸扶她: 0/66.md
      - 身体结构:
        - 体型特征:
          - 掌上娘: 0/31.md
        - 身体结构-数量:
          - 身体结构-数量: 0/10.md
          - 额外口: 0/7.md
          - 额外眼: 0/6.md
          - 额外阴茎: 0/8.md
          - 额外阴道: 0/13.md
        - 形态变化或描述:
          - 形态体积变化:
            - 乳房扩张: 0/111.md
            - 乳房缩小: 0/116.md
            - 睾丸扩张: 0/67.md
            - 臀部扩张: 0/50.md
            - 阴蒂增大: 0/143.md
          - 形态几何变化:
            - 阴茎乳头: 0/228.md
          - 形态描述:
            - 巨乳头: 0/83.md
            - 巨乳晕: 0/76.md
            - 巨阴蒂: 0/81.md
            - 巨阴道: 0/89.md
            - 巨乳:
              - 巨乳: 0/78.md
              - 爆乳: 0/80.md
              - 超乳: 0/79.md
            - 巨根:
              - 巨根: 0/85.md
              - 爆根: 0/86.md
              - 超根: 0/87.md
    - 物质:
      - 生物:
        - 精液: 0/204.md
        - 血液: 0/97.md
    - 社会相关:
      - 职业:
        - 收银员: 0/127.md
    - 行为与表现:
      - 行为产生:
        - 咬痕: 0/92.md
      - 行为:
        - 关系类:
          - NTR: 0/135.md
          - 猥亵: 0/137.md
          - 胁迫: 0/93.md
        - 变化相关:
          - 人体改造: 0/101.md
          - 身体替换: 0/103.md
        - 性行为:
          - 性行为: 0/25.md
          - 对象表现:
            - 自我乳交: 0/54.md
            - 自我口交: 0/53.md
            - BDSM:
              - BDSM: 0/71.md
              - TK: 0/110.md
              - 捆绑: 0/106.md
              - 睾丸虐待: 0/129.md
          - 性行为结果:
            - 处女膜破裂: 0/218.md
            - 精液溢出: 0/207.md
            - 精液腹: 0/206.md
          - 游戏性质:
            - 射精控制: 0/177.md
            - 肛门拔河: 0/125.md
          - 先前因素:
            - 性别变体性行为:
              - TS女×TS女: 0/225.md
              - TS女×女: 0/226.md
              - TS女×男: 0/227.md
            - 物理因素:
              - 壁尻: 0/145.md
            - 跨物种性行为:
              - 跨物种性行为: 0/191.md
              - 兽交: 0/37.md
              - 机械奸: 0/190.md
              - 虫奸: 0/192.md
              - 动物与Furry:
                - 人类和Furry性行为: 0/36.md
                - 动物和Furry性行为: 0/34.md
                - 动物性行为: 0/33.md
          - 性行为过程:
            - 往复表现:
              - 往复表现: 0/41.md
              - 乳头交: 0/167.md
              - 吮吸睾丸: 0/63.md
              - 揉睾丸: 0/61.md
              - 电动按摩: 0/221.md
              - 阴茎拍打: 0/180.md
            - 活塞表现:
              - 活塞表现: 0/40.md
              - 睾丸性交: 0/64.md
              - 肛交: 0/26.md
              - 脑交: 0/107.md
              - 腋窝性交: 0/45.md
              - 臀交: 0/52.md
              - 足交: 0/222.md
              - 阴蒂插入: 0/144.md
              - 乳交:
                - 乳交: 0/147.md
                - 下乳乳交: 0/168.md
                - 乳交口交: 0/153.md
                - 交替乳交: 0/156.md
                - 反向乳交: 0/150.md
                - 吮吸睾丸乳交: 0/152.md
                - 哺乳期乳交: 0/170.md
                - 垂直乳交: 0/149.md
                - 平胸乳交: 0/166.md
                - 抱胸乳交: 0/159.md
                - 模拟乳交: 0/169.md
                - 肛门舔舐乳交: 0/151.md
                - 马背式乳交: 0/155.md
                - 多人乳交:
                  - 三重乳交: 0/162.md
                  - 五重乳交: 0/164.md
                  - 侧双乳交: 0/161.md
                  - 六重乳交: 0/165.md
                  - 双乳交: 0/160.md
                  - 四重乳交: 0/163.md
                - 衣物乳交:
                  - 衣物乳交: 0/148.md
                  - 泳衣乳交: 0/173.md
                  - 胸罩型乳交: 0/171.md
                  - 隔衣乳交: 0/172.md
              - 口交:
                - 口交: 0/99.md
                - 侧卧口交: 0/158.md
                - 六九式口交: 0/157.md
                - 深喉: 0/217.md
                - 阴道口交: 0/209.md
            - 高潮表现:
              - 高潮表现: 0/42.md
              - 内射: 0/208.md
              - 射精: 0/56.md
              - 挟射: 0/154.md
              - 服装喷射: 0/39.md
              - 眼射: 0/205.md
              - 颜射: 0/118.md
        - 服装相关:
          - Cosplay: 0/197.md
        - 生育相关:
          - 堕胎: 0/4.md
          - 肛门分娩: 0/27.md
          - 母乳喂养:
            - 母乳喂养: 0/112.md
            - 百合授乳: 0/115.md
            - 相互哺乳: 0/113.md
        - 破坏类:
          - 食人: 0/126.md
          - 贯穿:
            - 贯穿: 0/19.md
            - 子宫颈穿透: 0/131.md
            - 穿刺: 0/17.md
        - 非破坏类:
          - 摄取: 0/5.md
          - 监禁: 0/184.md
          - 丸吞:
            - 丸吞: 0/18.md
            - 肛门吞噬: 0/30.md
            - 阴茎吞噬: 0/179.md
          - 舔舐:
            - 舔腋窝: 0/44.md
        - 生活相关:
          - 洗浴:
            - 洗浴: 0/203.md
            - 精液浴: 0/202.md
        - 生理或情绪相关:
          - 情绪行为:
            - 哭泣: 0/201.md
          - 生理行为:
            - 排尿: 0/139.md
      - 表现:
        - 面部:
          - 口交脸: 0/100.md
          - 阿黑颜: 0/15.md
  - 学术性质:
    - 学术性质: 0/3.md
    - 生物学:
      - 尸体: 0/188.md
    - 医学:
      - 功能解剖学:
        - 功能解剖学: 0/58.md
        - 泌尿生殖系统:
          - 泌尿生殖系统: 0/60.md
          - 女性生殖器官:
            - 处女膜: 0/219.md
            - 子宫: 0/132.md
            - 阴唇: 0/90.md
            - 阴蒂: 0/82.md
            - 阴道: 0/14.md
          - 男性生殖器官:
            - 睾丸: 0/62.md
            - 阴茎: 0/11.md
        - 消化系统:
          - 消化系统: 0/59.md
          - 肛门: 0/24.md
      - 疾病:
        - 疾病: 0/57.md
        - 02 肿瘤:
          - 02 肿瘤: 0/74.md
          - 痣: 0/75.md
        - 06 神经发育障碍:
          - 06 神经发育障碍: 0/185.md
          - 异食癖:
            - 异食癖: 0/186.md
            - 食粪: 0/187.md
        - 09 视觉系统疾病:
          - 09 视觉系统疾病: 0/94.md
          - 失明: 0/95.md
        - 13 消化系统疾病:
          - 13 消化系统疾病: 0/28.md
          - 肛门脱垂: 0/29.md
        - 14 皮肤疾病:
          - 14 皮肤疾病: 0/22.md
          - 白化病: 0/16.md
        - 16 泌尿生殖系统疾病:
          - 16 泌尿生殖系统疾病: 0/133.md
          - 子宫阴道脱垂: 0/134.md
        - 21 临床所见:
          - 21 临床所见: 0/48.md
          - 厌食症: 0/38.md
        - 22 外因等其他后果:
          - 22 外因等其他后果: 0/49.md
          - 子宫损伤: 0/211.md
          - 断肢: 0/20.md
          - 窒息: 0/47.md
          - 脑神经损伤: 0/109.md
          - 颅骨或面骨骨折: 0/108.md
      - 表面解剖学:
        - 表面解剖学: 0/23.md
        - 四肢:
          - 臀部: 0/51.md
          - 足部: 0/223.md
        - 头颈部:
          - 口: 0/9.md
          - 眼: 0/12.md
        - 躯干:
          - 乳头: 0/84.md
          - 乳房: 0/55.md
          - 乳晕: 0/77.md
          - 腋: 0/46.md